server:
    port: 8080
    context-path: /dong-manager

database: mysql
spring:
    datasource:
        url : jdbc:mysql://127.0.0.1:3306/dong?characterEncoding=UTF-8
        username : root
        password : 12345678
        driver-class-name : com.mysql.jdbc.Driver
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:



mybatis:
    type-aliases-package: com.yulaiz.dong.web.dao
    mapper-locations: classpath:mapper/*.xml
    configuration:
      map-underscore-to-camel-case: true

logging:
    file: ${catalina.base}/logs/test.log
    level:
        root: debug
        org.springframework.boot: error
        com.yulaiz.dong.web: debug

config:
    register-url: http://localhost:8080/dong-manager/register.html