server:
    port: 8080
    context-path: /dong

database: mysql
spring:
    datasource:
        url : jdbc:mysql://127.0.0.1:3306/dong?characterEncoding=UTF-8
        username : root
        password : 123456
        driver-class-name : com.mysql.jdbc.Driver
    redis:
      database:
      host: 127.0.0.1
      port: 6379
      password:



mybatis:
    type-aliases-package: com.yulaiz.dong.web.dao
    mapper-locations: classpath:mapper/*.xml
    configuration:
      map-underscore-to-camel-case: true

logging:
    file: logs/test.log
    level:
#        root: DEBUG
#        org.springframework.boot: DEBUG
        com.yulaiz.dong.web: DEBUG
